version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: garage_parrot-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garageParrot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  symfony:
    build: .
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
